### ISSUE TITLE
Handling of Multipart/Mixed Content in an Incoming Call

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-sdk#60] opened 2020-09-15 11:13 UTC
How do we handle a multipart/mixed Content and separate the SDP and the additional information in an Incoming SIP INVITE ?

**Comment by Viish** [comment] 2020-09-28 12:28
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/65

**Closed by Viish** 2020-09-28 12:28 UTC
