### ISSUE TITLE
linphone-sdk - Android "cmake --build ." command getting "FAILURE: Build failed with an exception." Error

### ISSUE THREAD

**Issue by nadeesh19** [BelledonneCommunications/linphone-sdk#166] opened 2021-07-07 01:26 UTC
I tried to compile linphone-sdk locally on macOS - Big Sur (version 11.3) linphone-sdk new version (5.0).
My java version is 14.
 i successfully completed this command.
`cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=arm64 -DENABLE_SILK=YES -DENABLE_G729==YES`

Then i used cmake --build . command. it returns this error now.
```

FAILURE: Build failed with an exception.

* Where:
Build file '<-Volume-path->/linphone-sdk/build/build.gradle' line: 147

* What went wrong:
A problem occurred evaluating root project 'build'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '<-Volume-path->/linphone-sdk/build/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 596ms
CMake Error at <-Volume-path->/linphone-sdk/cmake/Android/GradleClean.cmake:34 (message):
  Gradle clean failed


make[2]: *** [CMakeFiles/gradle-clean] Error 1
make[1]: *** [CMakeFiles/gradle-clean.dir/all] Error 2
make: *** [all] Error 2

```

i have added this code lines to correct files also 

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`
(and checked with gradle-6.1.1-all.zip also)

this is the 147 line in my build.gradle file
![Screenshot 2021-07-07 at 06 49 41](https://user-images.githubusercontent.com/10229154/124685772-90092300-deef-11eb-956f-1118d5815ed7.png)

i tried many times with deleting build folder in linphone-sdk which created by me, but same result.
need a help to resolve this.
thank you!

**Comment by Viish** [comment] 2021-07-07 07:10
Please don't create new issues for one I already closed...

Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/164

**Closed by Viish** 2021-07-07 07:10 UTC

**Comment by Viish** [comment] 2021-07-07 07:13
And given this:
`SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '<-Volume-path->/linphone-sdk/build/local.properties'.`
Seems you haven't properly set the path to your Android SDK...
