### ISSUE TITLE
Sip Message Event

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-sdk#116] opened 2021-02-18 14:19 UTC
> Indeed the method wasn't properly wrapped, it is now fixed: http://linphone.org/snapshots/docs/liblinphone/4.5/java/org/linphone/core/Core.html#addContentTypeSupport-java.lang.String-
> You need a SDK at least 4.5.0-beta.73+4a5c915.

@Viish 

1)Inspite of adding core.addContentType() method support for the incoming Sip Message I am not able to consume the incoming Sip  message ,I am still getting Unsupported Content Type Header Error.Apart from that  when my Message is rejected , a new Sip Message is generated automatically(I am not generating this event) ,and sent to server with some weird string in the content body causing to crash the server.

2) Whenever I deregister an account and try to register with the same account a Subscribe Event is generated for <sip:rls@linphone.org>

a)[Logs for the same] (https://www.linphone.org:444//tmp/602e2f17ed796_24b09505144b4a840fd3.gz)
b)Screenshots
![RejectedMessage on Client](https://user-images.githubusercontent.com/59530213/108344135-c6752880-7202-11eb-9d3c-a03733eab2e0.png)
![AutogeneratedMessageWithWeirdString](https://user-images.githubusercontent.com/59530213/108343137-99744600-7201-11eb-875a-79856e4b3e20.png)
![SipMessageFromServer](https://user-images.githubusercontent.com/59530213/108343261-c0327c80-7201-11eb-90a4-870e0210c9c5.png)
![SipSubscribe](https://user-images.githubusercontent.com/59530213/108343289-c7f22100-7201-11eb-9414-8d6fc82ec0bc.png)

Thanks in advance for your valuable feedback

**Comment by Viish** [comment] 2021-02-22 13:53
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/111

**Closed by Viish** 2021-02-22 13:53 UTC
