### ISSUE TITLE
Unable to compile linphone SDK with Xcode 12

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-sdk#63] opened 2020-09-22 06:23 UTC
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/jfalexvijay/Alex/linphone-sdk/build/WORK/ios-x86_64/Build/bctoolbox/src/bctoolbox.build/RelWithDebInfo-iphonesimulator/bctoolbox.build/Objects-normal/x86_64/mbedtls-F4C2FD15EF81378D.o src/crypto/mbedtls.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[1]: *** [/Users/jfalexvijay/Alex/linphone-sdk/build/WORK/ios-x86_64/Stamp/EP_bctoolbox/RelWithDebInfo-iphonesimulator/EP_bctoolbox-build] Error 65

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution CMake\ Rules /Users/jfalexvijay/Alex/linphone-sdk/build/ios-x86_64/Project.build/RelWithDebInfo-iphonesimulator/EP_bctoolbox.build/Script-76100FB3A7D745D8942E0D49.sh
(1 failure)
make: *** [/Users/jfalexvijay/Alex/linphone-sdk/build/ios-x86_64-prefix/src/ios-x86_64-stamp/RelWithDebInfo/ios-x86_64-build] Error 65

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution CMake\ Rules build/linphone-sdk.build/RelWithDebInfo/ios-x86_64.build/Script-43ECFB1487304641BAE5ECBA.sh
(1 failure)

<b>Plz help me on it.</b>

**Comment by KhairulRijl** [comment] 2020-09-22 11:42
i have same issue, maybe the problem is when building bctoolbox.build there is some warning and error. like this:
`/Users/khairulrijal/Documents/Dev-Environment/linphone-sdk/bctoolbox/include/bctoolbox/exception.hh:75:28: note: candidate function not viable: no known conversion from 'pumpstream' to 'std::ostream &' (aka 'basic_ostream<char> &') for 1st argument
BCTBX_PUBLIC std::ostream &operator<<(std::ostream &__os, const BctbxException &e);
                           ^
In file included from /Users/khairulrijal/Documents/Dev-Environment/linphone-sdk/bctoolbox/src/utils/exception.cc:29:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iomanip:47:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/istream:163:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:753:1: note: candidate template ignored: deduced conflicting types for parameter '_CharT' ('char' vs. 'BctbxException')
operator<<(basic_ostream<_CharT, _Traits>& __os, _CharT __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:814:1: note: candidate template ignored: could not match 'const _CharT *' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os, const _CharT* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1049:1: note: candidate template ignored: could not match 'basic_string<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os,
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1057:1: note: candidate template ignored: could not match 'basic_string_view<type-parameter-0-0, type-parameter-0-1>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os,
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1074:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-2>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os, shared_ptr<_Yp> const& __p)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1086:1: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-2, type-parameter-0-3>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os, unique_ptr<_Yp, _Dp> const& __p)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1093:1: note: candidate template ignored: could not match 'bitset<_Size>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os, const bitset<_Size>& __x)
^
In file included from /Users/khairulrijal/Documents/Dev-Environment/linphone-sdk/bctoolbox/src/utils/exception.cc:29:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iomanip:362:1: note: candidate template ignored: could not match '__iom_t8<type-parameter-0-2>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os, const __iom_t8<_MoneyT>& __x)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iomanip:482:1: note: candidate template ignored: could not match '__iom_t10<type-parameter-0-0>' against 'BctbxException'
operator<<(basic_ostream<_CharT, _Traits>& __os, const __iom_t10<_CharT>& __x)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iomanip:572:33: note: candidate template ignored: could not match '__quoted_output_proxy<type-parameter-0-0, type-parameter-0-2, type-parameter-0-1>' against 'BctbxException'
basic_ostream<_CharT, _Traits>& operator<<(
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iomanip:592:33: note: candidate template ignored: could not match '__quoted_proxy<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2>' against 'BctbxException'
basic_ostream<_CharT, _Traits>& operator<<(
                                ^
/Users/khairulrijal/Documents/Dev-Environment/linphone-sdk/bctoolbox/src/utils/exception.cc:74:41: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
        backtrace_symbols_fd(mArray + 1, mSize - 1, STDERR_FILENO);
        ~~~~~~~~~~~~~~~~~~~~             ~~~~~~^~~
/Users/khairulrijal/Documents/Dev-Environment/linphone-sdk/bctoolbox/src/utils/exception.cc:82:40: warning: implicit conversion loses integer precision: 'const size_t' (aka 'const unsigned long') to 'int' [-Wshorten-64-to-32]
        char **bt = backtrace_symbols(mArray, mSize);
                    ~~~~~~~~~~~~~~~~~         ^~~~~
/Users/khairulrijal/Documents/Dev-Environment/linphone-sdk/bctoolbox/src/utils/exception.cc:110:42: error: expected function body after function declarator
const char *BctbxException::what() const noexcept {
                                         ^
4 warnings and 3 errors generated.`

**Comment by KhairulRijl** [comment] 2020-09-22 12:39
@BelledonneComm

**Comment by jehandelalune** [comment] 2020-09-22 14:58
seems to be related to bad compiler detection.
Stick to xcode11 until we found a fix.

Interesting trace is:
-- The C compiler identification is unknown

**Comment by KhairulRijl** [comment] 2020-09-23 03:01
@jehandelalune seems like the problem on x86_64 architecture, because i have tried to build only for device architecture it's  normal

**Comment by jfalexvijay** [comment] 2020-09-23 06:26
@KhairulRijl Plz let us know how to compile without x86_64 architecture..

**Comment by KhairulRijl** [comment] 2020-09-23 07:47
@jfalexvijay before build, i have used ccmake for cmake-gui, there is options for ios arch, then you must delete x86_64, after that configure and generate

**Comment by jehandelalune** [comment] 2020-09-25 13:04
fixed by: https://github.com/BelledonneCommunications/linphone-sdk/commit/6665a41cc0679095073750656e1c9ce61b7f646d
it require cmake 3.18.2

**Closed** 2020-09-25 13:04 UTC

**Comment by jfalexvijay** [comment] 2020-09-30 09:45
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - /usr/local/bin/nasm
-- The ASM_NASM compiler identification is unknown
-- Found assembler: /usr/local/bin/nasm
-- CMAKE_ASM_NASM_COMPILER = /usr/local/bin/nasm
-- CMAKE_ASM_NASM_OBJECT_FORMAT = macho64
-- CMAKE_ASM_NASM_FLAGS =  -DMACHO -D__x86_64__ -g
-- SIMD extensions: x86_64 (WITH_SIMD = 1)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jfalexvijay/Alex/linphone-sdk/build/WORK/ios-x86_64/Build/turbojpeg
[ 52%] Forcing build for 'EP_turbojpeg'
[ 52%] Performing build step for 'EP_turbojpeg'
Scanning dependencies of target simd
[  0%] Building ASM_NASM object simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o
Traceback (most recent call last):
  File "/usr/local/bin/nasm", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/nasm/console.py", line 8, in main
    with open(sys.argv[1]) as f:
IOError: [Errno 2] No such file or directory: '-I/Users/jfalexvijay/Alex/linphone-sdk/build/WORK/ios-x86_64/Build/turbojpeg'
make[8]: *** [simd/CMakeFiles/simd.dir/x86_64/jsimdcpu.asm.o] Error 1
make[7]: *** [simd/CMakeFiles/simd.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [/Users/jfalexvijay/Alex/linphone-sdk/build/WORK/ios-x86_64/Stamp/EP_turbojpeg/EP_turbojpeg-build] Error 2
make[4]: *** [CMakeFiles/EP_turbojpeg.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ios-x86_64-prefix/src/ios-x86_64-stamp/ios-x86_64-build] Error 2
make[1]: *** [CMakeFiles/ios-x86_64.dir/all] Error 2
make: *** [all] Error 2
Js-MacBook-Pro-2:build root# cmake

**Comment by jfalexvijay** [comment] 2020-10-05 04:42
Hi,

I successfully compiled linphone with armv7 and arm64. And I added all the compiled linphone libraries to xcode project. But I am getting different error (plz check the attachment). Not sure what I am doing wrong.

Plz help me on this.

<img width="709" alt="Screenshot 2020-10-05 at 9 35 47 AM" src="https://user-images.githubusercontent.com/462630/95041051-38851f00-06f3-11eb-9002-215e0d2469b3.png">
