### ISSUE TITLE
P-Asserted-Identity iOS SDK [SWIFT]

### ISSUE THREAD

**Issue by Patresko** [BelledonneCommunications/linphone-sdk#186] opened 2021-10-20 08:12 UTC
How can I retrieve this information in SWIFT which im able to see in the log?

P-Asserted-Identity: "DECT ..." <sip:XXXX@XX.XX.XX.XX;user=phone>

I want to parse and show displayName for outgoing call instead of number.

**Comment by Viish** [comment] 2021-10-20 09:37
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/185

**Closed as completed by Viish** 2021-10-20 09:37 UTC
